Improve sqlalchemy.ext.orderinglist types
sqlalchemy/sqlalchemy2-stubs pull request #59
Opened 2021-04-08 14:11 UTC by MaicoTimmerman

### Description
I've expanded the type hints for the ordering list while testing for https://github.com/sqlalchemy/sqlalchemy/issues/6205.

### Checklist
This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

2021-04-09 21:17 UTC, bryanforbes requested changes

2021-04-09 21:17 UTC, bryanforbes commented on sqlalchemy-stubs/ext/orderinglist.pyi
> +    def __setitem__(self, index: Union[int, slice], entity: _T) -> None: ...
This should have the same signature as list:

```python
    @overload
    def __setitem__(self, i: int, o: _T) -> None: ...
    @overload
    def __setitem__(self, s: slice, o: Iterable[_T]) -> None: ...
```

2021-04-09 21:17 UTC, bryanforbes commented on sqlalchemy-stubs/orm/relationships.pyi
> +    collection_class: Optional[Union[Type, Callable[[], ...]]]
Since you're already editing this, `Type` should be changed to `Type[Any]`

2021-04-09 21:17 UTC, bryanforbes commented
Please make sure all functions have a return value

2021-04-10 21:48 UTC, bryanforbes commented on sqlalchemy-stubs/orm/relationships.pyi
> +    collection_class: Optional[Union[Type, Callable[[], ...]]]
`Type` will fail strict mode. `Type[Any]` will pass.

2021-04-12 14:57 UTC, bryanforbes commented on sqlalchemy-stubs/ext/orderinglist.pyi
> +    def __setitem__(self, index: Union[int, slice], entity: _T) -> None: ...
I think it would be good for us to add our own `_SupportsIndex` in `util/compat.pyi` and use that here instead of using a version check

2021-04-12 17:53 UTC, bryanforbes commented on sqlalchemy-stubs/util/compat.pyi
> +    from _typeshed import _SupportsIndex as SupportsIndex  # noqa
Since this isn't exposed in the actual compat file, this should be called as `_SupportsIndex`

2021-04-12 17:53 UTC, bryanforbes commented on sqlalchemy-stubs/util/compat.pyi
> +    class SupportsIndex(Protocol):
Same here

2021-04-12 18:26 UTC, bryanforbes approved these changes
This looks good. @zzzeek or @CaselIT, feel free to merge.

2021-04-12 18:33 UTC, merged

2021-04-12 18:33 UTC, CaselIT commented
thanks!